services:
  db:
    image: postgres:16-alpine
    container_name: adonis_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: adonis
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adonis -d app"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: adonis_adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
